version: 5.0.9.{build}.{branch}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
configuration: Release
shallow_clone: false
clone_depth: 1
clone_folder: C:\Repos\wolfmania
install:
- cmd: >-
    git rev-parse HEAD > gitRev.txt

    set /p GIT_COMMIT=<gitRev.txt

    echo Sanity check build id %APPVEYOR_BUILD_ID%

    curl -H "Content-Type: application/json" -X POST -d "{"""state""": """pending""", """description""": """Starting the appveyor build.""", """context""": """continuous-integration/appveyor"""}" https://api.github.com/repos/wolfman2000/stepmania/statuses/%GIT_COMMIT%
    
    echo Working on git commit %GIT_COMMIT%
    
    echo Running cmake now...

    choco install cmake
before_build:
- cmd: >-
    cd Build

    cmake -G "Visual Studio 14 2015" ..
build:
  project: C:\Repos\wolfmania\Build\StepMania.sln
  verbosity: normal
on_success:
- cmd: >-
    curl -H "Content-Type: application/json" -X POST -d "{"""state""": """success""", """description""": """Successfully compiled in appveyor.""", """context""": """continuous-integration/appveyor"""}" https://api.github.com/repos/wolfman2000/stepmania/statuses/%GIT_COMMIT%
on_failure:
- cmd: >-
    curl -H "Content-Type: application/json" -X POST -d "{"""state""": """failure""", """description""": """Build failure on appveyor.""", """context""": """continuous-integration/appveyor"""}" https://api.github.com/repos/wolfman2000/stepmania/statuses/%GIT_COMMIT%

