version: 5.0.9.{build}.{branch}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
configuration: Release
shallow_clone: false
clone_depth: 1
clone_folder: C:\Repos\wolfmania
install:
- cmd: >-
    echo Sanity check build id %APPVEYOR_BUILD_ID%

    echo Sanity check build number %APPVEYOR_BUILD_NUMBER%

    echo Sanity check build version %APPVEYOR_BUILD_VERSION%

    set GITHUB_API_URL=https://api.github.com/repos/wolfman2000/stepmania/statuses/%APPVEYOR_REPO_COMMIT%

    set GITHUB_API_PENDING="{"""state""": """pending""", """description""": """Starting the appveyor build.""", """context""": """continuous-integration/appveyor"""}"

    curl -H "application/vnd.github.v3+json" -H "Content-Type: application/json" -X POST -d %GITHUB_API_PENDING% %GITHUB_API_URL%
    
    echo Working on git commit %APPVEYOR_REPO_COMMIT%
    
    choco install cmake
before_build:
- cmd: >-
    cd Build

    cmake -G "Visual Studio 14 2015" ..
build:
  project: C:\Repos\wolfmania\Build\StepMania.sln
  verbosity: normal
on_success:
- cmd: >-
    set GITHUB_API_SUCCESS="{"""state""": """success""", """description""": """Successfully compiled in appveyor.""", """context""": """continuous-integration/appveyor"""}"

    curl -H "application/vnd.github.v3+json" -H "Content-Type: application/json" -X POST -d %GITHUB_API_SUCCESS% %GITHUB_API_URL%
on_failure:
- cmd: >-
    set GITHUB_API_FAILURE="{"""state""": """failure""", """description""": """Build failure on appveyor.""", """context""": """continuous-integration/appveyor"""}"

    curl -H "application/vnd.github.v3+json" -H "Content-Type: application/json" -X POST -d %GITHUB_API_FAILURE%  %GITHUB_API_URL%

