version: 5.0.9.{build}.{branch}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
configuration: Release
shallow_clone: true
clone_folder: C:\Repos\wolfmania
install:
- cmd: >-
    choco install cmake
before_build:
- cmd: >-
    git parse-rev --short HEAD > gitRev.txt

    set /p GIT_COMMIT=<gitRev.txt

    echo Working on git commit %GIT_COMMIT%
    
    echo Running cmake now...

    cd C:\Repos\wolfmania\Build

    cmake -G "Visual Studio 14 2015" ..
build:
  project: C:\Repos\wolfmania\Build\StepMania.sln
  verbosity: normal

