language: cpp

cache:
    directories:
      - $HOME/cmake

sudo: false

compiler:
    - clang
    - gcc

notifications:
    email: false
    irc: "chat.freenode.net#stepmania-devs"

addons:
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - nasm
            - libmad0-dev
            - libgtk2.0-dev
            - binutils-dev
            - libasound-dev
            - libpulse-dev
            - libjack-dev
            - libc6-dev
            - libogg-dev
            - libvorbis-dev
            - libbz2-dev
            - libjpeg8-dev
            - libpng12-dev
            - libxtst-dev
            - libxrandr-dev
            - libglu1-mesa-dev
            - mesa-common-dev
            - libglew-dev

install:
    -
      if [ "$CXX" == "g++" ]; then
        export CXX="g++-4.9";
        export CC="gcc-4.9";
      fi
    -
      if [ "$CXX" == "clang++" ]; then
        export ORIG_BUILD_DIR=$(pwd);
        cd ~;
        wget https://github.com/Viq111/travis-container-packets/releases/download/clang%2Blibcxx-3.4.2/clang_libcxx.tar.bz2;
        tar -xjf clang_libcxx.tar.bz2;
        rm clang_libcxx.tar.bz2;
        mv clang_libcxx clang;
        cd $ORIG_BUILD_DIR;
      fi

before_script:
    - bash .install-cmake.sh

script:
    - echo "Building StepMania now."
    - cd Build
    - $HOME/cmake/bin/cmake -DWITH_MP3=OFF -G 'Unix Makefiles' ..
    - make
