language: cpp

compiler:
    - clang
    - gcc

notifications:
    email: false
    irc: "chat.freenode.net#stepmania-devs"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    -
      if [ "$CXX" == "clang++" ]; then
        sudo add-apt-repository -y ppa:h-rayflood/llvm;
        sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main';
        wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
      fi
    - sudo apt-get update -qq
    - sudo apt-get autoremove -qq
    - echo "apt-get ready for installing."

install:
    - sudo apt-get install -y nasm -qq
    - sudo apt-get install -y libmad0-dev -qq
    - sudo apt-get install -y libgtk2.0-dev -qq
    - sudo apt-get install -y binutils-dev -qq
    - sudo apt-get install -y libasound-dev -qq
    - sudo apt-get install -y libpulse-dev -qq
    - sudo apt-get install -y libjack-dev -qq
    - sudo apt-get install -y libc6-dev -qq
    - sudo apt-get install -y libogg-dev -qq
    - sudo apt-get install -y libvorbis-dev -qq
    - sudo apt-get install -y libbz2-dev -qq
    - sudo apt-get install -y zlib1g-dev -qq
    - sudo apt-get install -y libjpeg8-dev -qq
    - sudo apt-get install -y libpng12-dev -qq
    - sudo apt-get install -y libxtst-dev -qq
    - sudo apt-get install -y libxrandr-dev -qq
    - sudo apt-get install -y libglu1-mesa-dev -qq
    - sudo apt-get install -y mesa-common-dev -qq
    - sudo apt-get install -y libglew-dev -qq
    - sudo apt-get install -y libstdc++-4.8-dev -qq

    - 
      if [ "$CXX" == "g++" ]; then
        sudo apt-get install gcc-4.8 g++-4.8 -qq;
        export CXX="g++-4.8";
        export CC="gcc-4.8";
      fi
    - 
      if [ "$CXX" == "clang++" ]; then
      sudo apt-get install --allow-unauthenticated libclang-3.7-dev clang-3.7;
      export CXX="clang++-3.7";
      export CC="clang-3.7";
      fi

    - echo "apt-get packages installed."

    - ./.travis-install-cmake.sh

script:
    - echo "Building StepMania now."
    - cmake -DWITH_PORTABLE_TOMCRYPT=ON -G 'Unix Makefiles'
    - make
